const { app, BrowserWindow, ipcMain, screen, safeStorage, session } = require('electron');
const path = require('path');
const fs = require('fs');
const isDev = !app.isPackaged;
let mainWindow;
let customerWindow;

function createMainWindow(){mainWindow=new BrowserWindow({width:1500,height:950,minWidth:1180,minHeight:720,backgroundColor:'#080b12',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false}});mainWindow.loadURL(isDev?'http://localhost:5173':`file://${path.join(__dirname,'../dist/index.html')}`);}
function createCustomerDisplay(displayId){if(customerWindow&&!customerWindow.isDestroyed()){customerWindow.focus();return;}const target=screen.getAllDisplays().find(d=>d.id===Number(displayId))||screen.getPrimaryDisplay();customerWindow=new BrowserWindow({x:target.bounds.x,y:target.bounds.y,width:target.bounds.width,height:target.bounds.height,fullscreen:true,frame:false,backgroundColor:'#080b12',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false}});if(isDev)customerWindow.loadURL('http://localhost:5173/?display=customer');else customerWindow.loadFile(path.join(__dirname,'../dist/index.html'),{query:{display:'customer'}});customerWindow.on('closed',()=>{customerWindow=null;});}
function printerList(){return mainWindow?.webContents?.getPrintersAsync().then(ps=>ps.map(p=>({name:p.name,displayName:p.displayName,description:p.description||'',status:p.status,isDefault:p.isDefault})))||Promise.resolve([]);}
function printHtml({html,deviceName,silent=true,pageSize}){const win=new BrowserWindow({show:false,width:800,height:1000,webPreferences:{contextIsolation:true,nodeIntegration:false}});return new Promise((resolve,reject)=>{win.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`);win.webContents.once('did-finish-load',()=>win.webContents.print({silent,deviceName:deviceName||undefined,printBackground:true,pageSize:pageSize||undefined},ok=>{win.close();ok?resolve(true):reject(new Error('Printer did not accept the job.'));}));win.webContents.once('did-fail-load',()=>{win.close();reject(new Error('Could not prepare print job.'));});}
const keyFile=()=>path.join(app.getPath('userData'),'pos-ai-key.bin');
function getAIKey(){if(process.env.OPENAI_API_KEY)return process.env.OPENAI_API_KEY;try{if(!safeStorage.isEncryptionAvailable())return '';return safeStorage.decryptString(fs.readFileSync(keyFile()));}catch{return '';}}
function setAIKey(value){if(!value)return false;if(!safeStorage.isEncryptionAvailable())throw new Error('Windows secure storage is unavailable.');fs.mkdirSync(app.getPath('userData'),{recursive:true});fs.writeFileSync(keyFile(),safeStorage.encryptString(value.trim()));return true;}
const realtimeTools=[{type:'function',name:'pos_action',description:'Operate the local restaurant POS. Use read actions for questions. Never invent records. Destructive, payment and high-value actions are confirmed by the local app.',parameters:{type:'object',properties:{action:{type:'string',enum:['snapshot','low_stock','list_products','add_customer','add_product','adjust_stock','create_combo','add_expense','add_rider','add_staff','create_purchase','delete_customer','delete_product','add_to_order','checkout','print_receipt','help']},name:{type:'string'},phone:{type:'string'},price:{type:'number'},quantity:{type:'number'},amount:{type:'number'},category:{type:'string'},item:{type:'string'},method:{type:'string'},description:{type:'string'}},required:['action'],additionalProperties:false}}];
function realtimeInstructions(context){return `You are the premium voice operator for MK Pizza & Ice Bar POS. Listen continuously, understand natural English, Urdu, Urdu-English mixed speech, accents, restaurant shorthand and incomplete requests. Speak naturally and briefly. Use the pos_action tool whenever a POS operation or business lookup is needed. Do not invent data. For deletion, checkout/payment, price changes or other high-value actions, call the tool; the local application will ask for confirmation. Current POS context: ${JSON.stringify(context||{}).slice(0,30000)}`;}
function realtimeSession(context){return{type:'realtime',model:'gpt-realtime-2.1',output_modalities:['audio'],instructions:realtimeInstructions(context),tools:realtimeTools,tool_choice:'auto',audio:{input:{turn_detection:{type:'server_vad',create_response:true,interrupt_response:true,silence_duration_ms:650,threshold:0.5}},output:{voice:'marin'}}};}
function localAICommand(message,context={}){const q=String(message||'').toLowerCase().trim(),o=context.orders||[],inv=context.inventory||[],pro=context.products||[],cus=context.customers||[],exp=context.expenses||[];const money=n=>`Rs ${Number(n||0).toLocaleString()}`;const product=pro.find(x=>q.includes(String(x.name||'').toLowerCase()));const item=inv.find(x=>q.includes(String(x.name||'').toLowerCase()));
 if(/\b(help|what can you do|commands)\b/.test(q))return{action:'help',args:{}};
 if(/\b(low stock|low inventory|reorder|stock alert)\b/.test(q))return{action:'low_stock',args:{}};
 if(/\b(sales|revenue|turnover|how much.*sold|how much.*sale)\b/.test(q))return{action:'snapshot',args:{}};
 if(/\b(expense|expenses|costs?)\b/.test(q))return{action:'snapshot',args:{}};
 if(/\b(customer|customers|clients)\b/.test(q)&&/how many|count|list|show/.test(q))return{action:'snapshot',args:{}};
 if(/\b(menu|products|items)\b/.test(q)&&/how many|count|list|show/.test(q))return{action:'list_products',args:{}};
 const add=/\b(add|put)\s+(\d+)?\s*(?:x\s*)?(.+?)(?:\s+to\s+(?:my\s+)?order)?$/i.exec(message||'');if(add&&product)return{action:'add_to_order',args:{item:product.name,quantity:Number(add[2]||1)}};
 const stock=/\b(?:add|increase|receive|remove|decrease|subtract)\s+(\d+(?:\.\d+)?)\s+(?:of\s+)?(.+?)\s+(?:stock|inventory)?$/i.exec(message||'');if(stock&&item){const n=Number(stock[1])*(/\b(remove|decrease|subtract)\b/i.test(stock[0])?-1:1);return{action:'adjust_stock',args:{item:item.name,quantity:n}};}
 const addCustomer=/\b(?:add|create)\s+(?:customer|client)\s+(.+?)(?:\s+\+?(\d[\d\s-]{7,}))?$/i.exec(message||'');if(addCustomer)return{action:'add_customer',args:{name:addCustomer[1].trim(),phone:addCustomer[2]||''}};
 const addProduct=/\b(?:add|create)\s+(?:product|menu item)\s+(.+?)\s+(?:for|at)\s+(\d+(?:\.\d+)?)\b/i.exec(message||'');if(addProduct)return{action:'add_product',args:{name:addProduct[1].trim(),price:Number(addProduct[2])}};
 if(/\b(print|reprint)\b.*\b(receipt|bill)\b/.test(q))return{action:'print_receipt',args:{}};
 if(product&&/\b(add|order|want|give|put)\b/.test(q))return{action:'add_to_order',args:{item:product.name,quantity:1}};
 return{action:'help',args:{}};}
async function aiCommand({message,context}){const apiKey=getAIKey();if(!apiKey)return localAICommand(message,context);const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:'gpt-5.6-luna',instructions:realtimeInstructions(context),input:message,tools:realtimeTools,tool_choice:'required'})});if(!response.ok)throw new Error(`AI service error ${response.status}: ${await response.text()}`);const body=await response.json();const call=(body.output||[]).find(x=>x.type==='function_call'&&x.name==='pos_action');if(!call)return{action:'help',args:{}};let args={};try{args=JSON.parse(call.arguments||'{}')}catch{}return{action:args.action||'help',args};}
async function realtimeConnect({sdp,context}){const apiKey=getAIKey();if(!apiKey)throw new Error('Standalone mode: use the POS Copilot for offline AI. Cloud voice requires an API key.');const tokenRes=await fetch('https://api.openai.com/v1/realtime/client_secrets',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${apiKey}`},body:JSON.stringify({expires_after:{anchor:'created_at',seconds:600},session:realtimeSession(context)})});if(!tokenRes.ok)throw new Error(`Realtime authentication error ${tokenRes.status}: ${await tokenRes.text()}`);const token=await tokenRes.json();if(!token.value)throw new Error('Realtime client secret was not returned.');const callRes=await fetch('https://api.openai.com/v1/realtime/calls',{method:'POST',headers:{Authorization:`Bearer ${token.value}`,'Content-Type':'application/sdp'},body:sdp});if(!callRes.ok)throw new Error(`Realtime connection error ${callRes.status}: ${await callRes.text()}`);return await callRes.text();}
app.whenReady().then(()=>{session.defaultSession.setPermissionRequestHandler((webContents,permission,callback)=>{if(permission==='media')return callback(true);callback(true);});session.defaultSession.setPermissionCheckHandler((webContents,permission)=>permission==='media'||permission==='notifications');createMainWindow();ipcMain.handle('system:displays',()=>screen.getAllDisplays().map(d=>({id:d.id,bounds:d.bounds,scaleFactor:d.scaleFactor})));ipcMain.handle('display:open',(_,id)=>{createCustomerDisplay(id);return true;});ipcMain.handle('display:close',()=>{if(customerWindow&&!customerWindow.isDestroyed())customerWindow.close();return true;});ipcMain.handle('app:version',()=>app.getVersion());ipcMain.handle('printers:list',()=>printerList());ipcMain.handle('printer:print',(_,payload)=>printHtml(payload));ipcMain.handle('ai:key:status',()=>Boolean(getAIKey()));ipcMain.handle('ai:key:set',(_,key)=>setAIKey(key));ipcMain.handle('ai:command',(_,payload)=>aiCommand(payload));ipcMain.handle('ai:realtime:connect',(_,payload)=>realtimeConnect(payload));app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createMainWindow();});});
app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit();});
