const n=v=>Number(v||0);
const find=(rows,q,fields=['name'])=>rows.find(r=>fields.some(k=>String(r?.[k]??'').toLowerCase()===q.toLowerCase()))||rows.find(r=>fields.some(k=>String(r?.[k]??'').toLowerCase().includes(q.toLowerCase())));
export function posAI({text,products=[],inventory=[],customers=[],suppliers=[],riders=[],staff=[],expenses=[],purchases=[],orders=[],setProducts,setInventory,setCustomers,setSuppliers,setRiders,setStaff,setExpenses,setPurchases,notify,log}){
 const t=String(text||'').trim(), l=t.toLowerCase();
 const moneyWord=t.match(/(?:rs\.?|pkr)?\s*(\d[\d,]*(?:\.\d+)?)/i); const amount=moneyWord?n(moneyWord[1].replaceAll(',','')):0;
 const result=(message,action=null)=>({message,action});
 if(/^(add|create|new)\s+(customer|client)/i.test(t)){const m=t.match(/(?:customer|client)\s+(.+?)(?:\s+(?:phone|number)\s+([\d+ -]+))?$/i);const row={id:Date.now(),name:m?.[1]||'New Customer',phone:m?.[2]||'',address:'',points:0,visits:0};setCustomers?.(x=>[...x,row]);log?.('AI_CUSTOMER_CREATE',row.name);return result(`Customer ${row.name} added.`)}
 if(/^(add|create|new)\s+(product|item)/i.test(t)){const m=t.match(/(?:product|item)\s+(.+?)(?:\s+(?:price|at)\s+(\d+(?:\.\d+)?))?$/i);const row={id:Date.now(),name:m?.[1]||'New Product',cat:'AI',price:n(m?.[2]),emoji:'✨',sku:`AI-${Date.now()}`,active:true,cost:0,recipe:[]};setProducts?.(x=>[...x,row]);log?.('AI_PRODUCT_CREATE',row.name);return result(`Product ${row.name} added.`)}
 if(/(?:adjust|add|increase|decrease|remove|set)\s+(?:stock|inventory)/i.test(t)){const m=t.match(/(?:stock|inventory)\s+(?:for\s+)?(.+?)\s+(?:by|to|=)\s*(-?\d+(?:\.\d+)?)/i);const item=m&&find(inventory,m[1]);if(item){const delta=n(m[2]),target=l.includes('set ')?delta:item.qty+delta;const qty=Math.max(0,target);setInventory?.(xs=>xs.map(x=>x.id===item.id?{...x,qty}:x));log?.('AI_STOCK_ADJUST',`${item.name}: ${item.qty} → ${qty}`);return result(`Stock updated: ${item.name} is now ${qty} ${item.unit}.`)}return result('I could not identify the inventory item. Say: “adjust stock Chicken Fillet by 5”.')}
 if(/(?:make|create|add)\s+(?:a\s+)?(?:deal|combo)/i.test(t)){const m=t.match(/(?:deal|combo)\s+(.+?)(?:\s+(?:for|at|price)\s+(\d+(?:\.\d+)?))?$/i);const row={id:Date.now(),name:m?.[1]||'AI Combo',cat:'Combos',price:n(m?.[2]),emoji:'✨',sku:`COMBO-${Date.now()}`,active:true,cost:0,recipe:[]};setProducts?.(x=>[...x,row]);log?.('AI_COMBO_CREATE',row.name);return result(`Combo/deal ${row.name} created. You can edit its items and price in Menu & Combos.`)}
 if(/(?:add|create|new)\s+(?:purchase|demand|demand purchase|po)/i.test(t)){const row={id:Date.now(),supplierId:suppliers[0]?.id||'',items:t,total:amount,status:'Draft',invoice:`AI-${Date.now()}`};setPurchases?.(x=>[...x,row]);log?.('AI_PURCHASE_CREATE',row.invoice);return result(`Purchase request created for ${amount?'Rs '+amount:'the requested items'}.`)}
 if(/(?:add|create|record)\s+(?:expense|cost)/i.test(t)){const cats=['Salary','Staff-Food','Rent','Utilities','Demands','Fuel','Wastage','Packaging','Maintenance','Marketing','Transport','Other'];const c=cats.find(x=>l.includes(x.toLowerCase()))||'Other';const row={id:Date.now(),title:t,category:c,amount,payee:'AI command',date:new Date().toISOString().slice(0,10),method:'Cash',note:'Created by POS AI'};setExpenses?.(x=>[row,...x]);log?.('AI_EXPENSE',`${c} ${amount}`);return result(`Expense recorded under ${c}: Rs ${amount.toLocaleString()}.`)}
 if(/(?:add|create|new)\s+rider/i.test(t)){const m=t.match(/rider\s+(.+?)(?:\s+(?:phone|number)\s+([\d+ -]+))?$/i);const row={id:Date.now(),name:m?.[1]||'New Rider',phone:m?.[2]||'',vehicle:'Bike',area:'',perOrder:100,perKm:25,status:'Available'};setRiders?.(x=>[...x,row]);log?.('AI_RIDER_CREATE',row.name);return result(`Rider ${row.name} added with default delivery costs.`)}
 if(/(?:add|create|new)\s+(?:staff|employee)/i.test(t)){const m=t.match(/(?:staff|employee)\s+(.+)$/i);const row={id:Date.now(),name:m?.[1]||'New Staff',role:'Staff',phone:'',pin:'',salary:0,status:'Active'};setStaff?.(x=>[...x,row]);log?.('AI_STAFF_CREATE',row.name);return result(`Staff profile ${row.name} added.`)}
 if(/sales|revenue|business|performance|how are we|today/i.test(l)){const sales=orders.reduce((s,o)=>s+n(o.total),0),avg=orders.length?sales/orders.length:0;const low=inventory.filter(x=>n(x.qty)<=n(x.reorder));return result(`Business snapshot: ${orders.length} orders, Rs ${sales.toLocaleString()} sales, Rs ${Math.round(avg).toLocaleString()} average ticket, ${low.length} low-stock items.`)}
 if(/low stock|reorder|inventory/i.test(l)){const low=inventory.filter(x=>n(x.qty)<=n(x.reorder));return result(low.length?`Reorder radar: ${low.map(x=>`${x.name} (${x.qty} ${x.unit})`).join(', ')}.`:'Inventory looks healthy right now.')}
 if(/expense|spend|cost/i.test(l)){const total=expenses.reduce((s,x)=>s+n(x.amount),0);return result(`Recorded expenses total Rs ${total.toLocaleString()} across ${expenses.length} entries.`)}
 if(/customer/i.test(l))return result(`${customers.length} customer profiles are stored locally.`);
 if(/product|menu/i.test(l))return result(`${products.length} products are configured. I can create products, combos and deals by command.`);
 if(/print|receipt|sale receipt/i.test(l))return result('Receipt printing is controlled by the Windows printer service. After a paid sale, use the receipt action; I can also prepare a print request once a sale number is specified.');
 return result('I can execute POS commands. Examples: “add customer Ali phone 03001234567”, “add product Zinger Burger price 650”, “adjust stock Chicken Fillet by -2”, “make combo Burger + Fries for 999”, “add expense Fuel 2500”, “create rider Ahmed phone 0300…”, “create purchase Chicken Fillet 20kg”.');
}
