import './aiOverlay.css';

const KEYS={products:'pos-products',inventory:'pos-inventory',customers:'pos-customers',suppliers:'pos-suppliers',riders:'pos-riders',staff:'pos-staff',expenses:'pos-expenses',purchases:'pos-purchases',orders:'pos-orders'};
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const id=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const money=n=>`Rs ${Number(n||0).toLocaleString()}`;
const data=()=>({products:read(KEYS.products),inventory:read(KEYS.inventory),customers:read(KEYS.customers),suppliers:read(KEYS.suppliers),riders:read(KEYS.riders),staff:read(KEYS.staff),expenses:read(KEYS.expenses),purchases:read(KEYS.purchases),orders:read(KEYS.orders)});
function audit(action,detail){const a=read('pos-audit');a.unshift({id:id('ai'),time:new Date().toLocaleString(),user:'POS AI',action,detail});save('pos-audit',a.slice(0,1000));}
function speak(text){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.98;u.pitch=1;speechSynthesis.speak(u)}catch{}}
function context(){const d=data();return {products:d.products.map(x=>({id:x.id,name:x.name,price:x.price,cat:x.cat,active:x.active})),inventory:d.inventory.map(x=>({id:x.id,name:x.name,qty:x.qty,reorder:x.reorder,unit:x.unit})),customers:d.customers.slice(0,100).map(x=>({id:x.id,name:x.name,phone:x.phone})),riders:d.riders.map(x=>({id:x.id,name:x.name,phone:x.phone,perOrder:x.perOrder,perKm:x.perKm,status:x.status})),staff:d.staff.map(x=>({id:x.id,name:x.name,role:x.role,status:x.status})),expenses:d.expenses.slice(0,100).map(x=>({category:x.category,amount:x.amount,date:x.date,title:x.title})),orders:d.orders.slice(0,100).map(x=>({id:x.id,no:x.no,total:x.total,method:x.method,status:x.status}))};}
function refresh(){window.dispatchEvent(new Event('pos-ai-changed'));setTimeout(()=>location.reload(),500)}
function findProduct(name){const q=String(name||'').toLowerCase();return data().products.find(x=>x.name.toLowerCase()===q)||data().products.find(x=>x.name.toLowerCase().includes(q));}
function addToCart(name,qty){const p=findProduct(name);if(!p)return false;const buttons=[...document.querySelectorAll('.product')];let b=buttons.find(x=>x.innerText.toLowerCase().includes(p.name.toLowerCase()));if(!b)b=buttons.find(x=>x.innerText.toLowerCase().includes(String(name).toLowerCase()));if(!b)return false;for(let i=0;i<Math.max(1,Number(qty||1));i++)b.click();return true}
function printReceipt(order){const s=read('pos-settings',{}),html=`<html><head><meta charset="utf-8"><style>@page{margin:3mm;width:80mm}body{font-family:Arial;width:72mm;font-size:12px}h2{text-align:center;margin:4px 0}p{margin:3px 0}.line{display:flex;justify-content:space-between}.total{font-size:16px;font-weight:bold;border-top:1px solid #000;padding-top:5px;margin-top:6px}</style></head><body><h2>${esc(s.companyName||'MK Pizza & Ice Bar')}</h2><p style="text-align:center">${esc(s.address||'')}<br>${esc(s.phone||'')}</p><p>Order: ${esc(order.no||order.id)}<br>${new Date().toLocaleString()}<br>Payment: ${esc(order.method||'Cash')}</p>${(order.items||[]).map(x=>`<div class="line"><span>${x.qty} × ${esc(x.name)}</span><span>${money(x.qty*x.price)}</span></div>`).join('')}<div class="line total"><span>TOTAL</span><span>${money(order.total)}</span></div><p style="text-align:center;margin-top:12px">Thank you!</p></body></html>`;return window.posDesktop?.print?window.posDesktop.print({html}):Promise.resolve(false)}

async function perform(action,args){
 const d=data();
 if(['delete_customer','delete_product','checkout'].includes(action)){
   const target=action==='checkout'?'the current order':(args.name||'the selected record');
   if(!confirm(`POS AI wants to ${action.replaceAll('_',' ')} ${target}. Continue?`))return 'Cancelled.';
 }
 if(action==='snapshot'){const sales=d.orders.reduce((s,o)=>s+Number(o.total||0),0),exp=d.expenses.reduce((s,x)=>s+Number(x.amount||0),0),low=d.inventory.filter(x=>Number(x.qty)<=Number(x.reorder));return `Business monitor: ${d.orders.length} orders, ${money(sales)} sales, ${money(exp)} expenses, ${low.length} low-stock items.`;}
 if(action==='low_stock'){const low=d.inventory.filter(x=>Number(x.qty)<=Number(x.reorder));return low.length?`Low stock: ${low.map(x=>`${x.name} ${x.qty} ${x.unit||''}`).join(', ')}.`:'No low-stock alerts.';}
 if(action==='list_products')return d.products.length?`There are ${d.products.length} menu items. Top items include ${d.products.slice(0,8).map(x=>x.name).join(', ')}.`:'No products found.';
 if(action==='help')return 'I can understand natural voice commands, answer business questions, add or edit POS records, adjust stock, create combos, manage riders and staff, create expenses and purchases, take orders, checkout and print receipts.';
 if(action==='add_customer'){const row={id:Date.now(),name:String(args.name||'New Customer').trim(),phone:String(args.phone||''),address:'',points:0,visits:0};save(KEYS.customers,[row,...d.customers]);audit('AI_CUSTOMER_CREATE',row.name);refresh();return `Added customer ${row.name}.`;}
 if(action==='add_product'){const row={id:Date.now(),name:String(args.name||'New Item').trim(),cat:String(args.category||'AI'),price:Number(args.price||0),emoji:'✨',sku:`AI-${Date.now()}`,active:true,cost:0,recipe:[]};save(KEYS.products,[...d.products,row]);audit('AI_PRODUCT_CREATE',row.name);refresh();return `Added ${row.name} at ${money(row.price)}.`;}
 if(action==='adjust_stock'){const q=String(args.item||args.name||'').toLowerCase();const item=d.inventory.find(x=>x.name.toLowerCase().includes(q));if(!item)return 'I could not find that stock item.';const delta=Number(args.quantity||0),qty=Math.max(0,Number(item.qty||0)+delta);save(KEYS.inventory,d.inventory.map(x=>x.id===item.id?{...x,qty}:x));audit('AI_STOCK_ADJUST',`${item.name}: ${item.qty} → ${qty}`);refresh();return `${item.name} stock is now ${qty} ${item.unit||''}.`;}
 if(action==='create_combo'){const row={id:Date.now(),name:String(args.name||'AI Combo'),cat:'Combos',price:Number(args.price||0),emoji:'✨',sku:`COMBO-${Date.now()}`,active:true,cost:0,recipe:[],components:[]};save(KEYS.products,[...d.products,row]);audit('AI_COMBO_CREATE',row.name);refresh();return `Created ${row.name}. You can add its component items in Menu & Combos.`;}
 if(action==='add_expense'){const row={id:Date.now(),title:String(args.description||args.name||'AI expense'),category:String(args.category||'Other'),amount:Number(args.amount||0),payee:'POS AI',date:new Date().toISOString().slice(0,10),method:String(args.method||'Cash'),note:'Created by POS AI'};save(KEYS.expenses,[row,...d.expenses]);audit('AI_EXPENSE',`${row.category} ${row.amount}`);refresh();return `Recorded ${row.category} expense of ${money(row.amount)}.`;}
 if(action==='add_rider'){const row={id:Date.now(),name:String(args.name||'New Rider'),phone:String(args.phone||''),vehicle:'Bike',area:'',perOrder:100,perKm:25,status:'Available'};save(KEYS.riders,[...d.riders,row]);audit('AI_RIDER_CREATE',row.name);refresh();return `Rider ${row.name} added.`;}
 if(action==='add_staff'){const row={id:Date.now(),name:String(args.name||'New Staff'),role:String(args.category||'Staff'),phone:String(args.phone||''),pin:'',salary:Number(args.amount||0),status:'Active'};save(KEYS.staff,[...d.staff,row]);audit('AI_STAFF_CREATE',row.name);refresh();return `Staff profile ${row.name} added.`;}
 if(action==='create_purchase'){const row={id:Date.now(),supplierId:d.suppliers[0]?.id||'',items:String(args.description||args.item||''),total:Number(args.amount||0),status:'Draft',invoice:`AI-${Date.now()}`};save(KEYS.purchases,[row,...d.purchases]);audit('AI_PURCHASE_CREATE',row.items);refresh();return `Purchase demand created for ${row.items||'the requested items'}.`;}
 if(action==='delete_customer'){const q=String(args.name||'').toLowerCase();const row=d.customers.find(x=>x.name.toLowerCase().includes(q));if(!row)return 'Customer not found.';save(KEYS.customers,d.customers.filter(x=>x.id!==row.id));audit('AI_CUSTOMER_DELETE',row.name);refresh();return `Deleted customer ${row.name}.`;}
 if(action==='delete_product'){const q=String(args.name||args.item||'').toLowerCase();const row=d.products.find(x=>x.name.toLowerCase().includes(q));if(!row)return 'Product not found.';save(KEYS.products,d.products.filter(x=>x.id!==row.id));audit('AI_PRODUCT_DELETE',row.name);refresh();return `Deleted product ${row.name}.`;}
 if(action==='add_to_order'){const ok=addToCart(args.item||args.name,args.quantity||1);return ok?`Added ${args.quantity||1} ${args.item||args.name} to the current order.`:'I could not find that menu item on the current POS screen.';}
 if(action==='checkout'){const b=[...document.querySelectorAll('.payGrid button')].find(x=>/cash/i.test(x.innerText));if(b&&!b.disabled){b.click();audit('AI_CHECKOUT','Cash checkout by voice');return 'Order placed and sent to the kitchen.';}return 'The current order is empty or the POS is not ready for payment.';}
 if(action==='print_receipt'){const o=d.orders[0];if(!o)return 'There is no sale to print yet.';await printReceipt(o);audit('AI_PRINT_RECEIPT',o.no||o.id);return `Printing receipt ${o.no||''}.`;}
 return 'I could not complete that POS action.';
}

function mount(){if(document.getElementById('posAiDock'))return;const root=document.createElement('div');root.id='posAiDock';root.innerHTML=`<button id="posAiFab" aria-label="POS AI">✦ <span>AI</span></button><div id="posAiPanel" hidden><div class="aiHead"><div><b>POS AI Operator</b><small id="posAiMode">GPT voice operator</small></div><button id="posAiClose">×</button></div><div id="posAiStatus">Starting AI…</div><div class="aiQuick"><button data-c="What are sales today?">Sales</button><button data-c="What is low stock?">Stock</button><button data-c="What can you do?">Help</button></div><div id="posAiLog"></div><div class="aiInput"><input id="posAiInput" placeholder="Talk naturally…"><button id="posAiMic">🎙</button><button id="posAiSend">➤</button></div><div id="posAiSetup" hidden><input id="posAiKey" type="password" placeholder="OpenAI API key"><button id="posAiSave">Connect AI</button><small>Your key is encrypted by Windows secure storage and is never placed in renderer code.</small></div></div>`;document.body.appendChild(root);
 const panel=root.querySelector('#posAiPanel'),logBox=root.querySelector('#posAiLog'),input=root.querySelector('#posAiInput'),status=root.querySelector('#posAiStatus'),setup=root.querySelector('#posAiSetup');
 const add=(who,msg)=>{const el=document.createElement('div');el.className=`aiMsg ${who}`;el.innerHTML=`<b>${who==='user'?'You':'AI'}</b><span>${esc(msg)}</span>`;logBox.appendChild(el);logBox.scrollTop=logBox.scrollHeight;};
 let recognition=null, listening=false, busy=false;
 const startListening=()=>{if(!recognition||listening||busy)return;try{recognition.start()}catch{}};
 const run=async(q)=>{if(!q||busy)return;busy=true;add('user',q);status.textContent='Thinking…';try{const result=await window.posDesktop.aiCommand({message:q,context:context()});const msg=await perform(result.action,result.args||{});add('ai',msg);speak(msg);}catch(e){add('ai',e.message||'AI connection failed.');speak('I could not connect to the AI service.');}finally{busy=false;status.textContent=listening?'Listening automatically…':'Ready';if(listening)setTimeout(startListening,350);}};
 root.querySelector('#posAiFab').onclick=()=>panel.hidden=!panel.hidden;root.querySelector('#posAiClose').onclick=()=>panel.hidden=true;root.querySelector('#posAiSend').onclick=()=>{const q=input.value.trim();input.value='';run(q)};input.onkeydown=e=>{if(e.key==='Enter'){const q=input.value.trim();input.value='';run(q)}};root.querySelectorAll('.aiQuick button').forEach(b=>b.onclick=()=>run(b.dataset.c));
 root.querySelector('#posAiSave').onclick=async()=>{const key=root.querySelector('#posAiKey').value.trim();if(!key)return;try{await window.posDesktop.setAIKey(key);setup.hidden=true;status.textContent='AI connected. Listening automatically…';initializeVoice();}catch(e){status.textContent=e.message}};
 const initializeVoice=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){status.textContent='AI connected. This Electron runtime has no speech recognition; typing is available.';return;}recognition=new SR();recognition.lang='en-PK';recognition.continuous=false;recognition.interimResults=false;recognition.onstart=()=>{listening=true;status.textContent='Listening automatically…'};recognition.onend=()=>{listening=false;if(window.posDesktop?.aiKeyStatus)window.posDesktop.aiKeyStatus().then(ok=>{if(ok)setTimeout(startListening,350)}).catch(()=>{})};recognition.onerror=e=>{listening=false;if(e.error==='not-allowed'||e.error==='service-not-allowed')status.textContent='Microphone permission is required. Click the mic once, then automatic listening will continue.';else if(e.error!=='aborted')status.textContent=`Voice: ${e.error}`};recognition.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript?.trim();if(text){input.value=text;run(text)}};startListening();};
 window.posDesktop?.aiKeyStatus?.().then(ok=>{if(ok){setup.hidden=true;initializeVoice()}else{status.textContent='Connect AI once to enable automatic GPT voice listening.';setup.hidden=false;panel.hidden=false}}).catch(()=>{setup.hidden=false;panel.hidden=false;status.textContent='Connect AI to enable GPT voice operator.'});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
