import './aiOverlay.css';
const K={p:'pos-products',i:'pos-inventory',c:'pos-customers',r:'pos-riders',s:'pos-staff',e:'pos-expenses',q:'pos-purchases',o:'pos-orders'};
const rd=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};const sv=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const money=n=>`Rs ${Number(n||0).toLocaleString()}`;const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function audit(a,d){const x=rd('pos-audit');x.unshift({id:`ai-${Date.now()}`,time:new Date().toLocaleString(),user:'POS AI',action:a,detail:d});sv('pos-audit',x.slice(0,1000));}
function ctx(){return{products:rd(K.p).map(x=>({id:x.id,name:x.name,price:x.price,cat:x.cat})),inventory:rd(K.i).map(x=>({id:x.id,name:x.name,qty:x.qty,reorder:x.reorder,unit:x.unit})),customers:rd(K.c).slice(0,100).map(x=>({id:x.id,name:x.name,phone:x.phone})),riders:rd(K.r).map(x=>({id:x.id,name:x.name,phone:x.phone,perOrder:x.perOrder,perKm:x.perKm,status:x.status})),staff:rd(K.s).map(x=>({id:x.id,name:x.name,role:x.role,status:x.status})),orders:rd(K.o).slice(0,100).map(x=>({id:x.id,no:x.no,total:x.total,method:x.method,status:x.status})),expenses:rd(K.e).slice(0,100).map(x=>({title:x.title,category:x.category,amount:x.amount,date:x.date}))};}
function refresh(){setTimeout(()=>location.reload(),350)}
function findProduct(n){const q=String(n||'').toLowerCase();const p=rd(K.p);return p.find(x=>x.name.toLowerCase()===q)||p.find(x=>x.name.toLowerCase().includes(q));}
function addCart(n,q=1){const p=findProduct(n);if(!p)return false;const b=[...document.querySelectorAll('.product')].find(x=>x.innerText.toLowerCase().includes(p.name.toLowerCase()));if(!b)return false;for(let i=0;i<Number(q);i++)b.click();return true;}
async function printReceipt(o){const s=rd('pos-settings',{}),html=`<html><head><style>@page{margin:3mm;width:80mm}body{font:12px Arial;width:72mm}.c{text-align:center}.l{display:flex;justify-content:space-between}.t{font-weight:bold;font-size:16px;border-top:1px solid #000;margin-top:6px;padding-top:5px}</style></head><body><h2 class=c>${esc(s.companyName||'MK Pizza & Ice Bar')}</h2><p class=c>${esc(s.address||'')}<br>${esc(s.phone||'')}</p><p>Order: ${esc(o.no||o.id)}<br>${new Date().toLocaleString()}<br>Payment: ${esc(o.method||'Cash')}</p>${(o.items||[]).map(x=>`<div class=l><span>${x.qty} × ${esc(x.name)}</span><span>${money(x.qty*x.price)}</span></div>`).join('')}<div class="l t"><span>TOTAL</span><span>${money(o.total)}</span></div><p class=c>Thank you!</p></body></html>`;return window.posDesktop?.print?.({html});}
async function act(a,x){const p=rd(K.p),i=rd(K.i),c=rd(K.c),r=rd(K.r),s=rd(K.s),e=rd(K.e),q=rd(K.q),o=rd(K.o);if(['delete_customer','delete_product','checkout'].includes(a)&&!confirm(`POS AI wants to ${a.replaceAll('_',' ')} ${x.name||'the current order'}. Continue?`))return'Cancelled.';
 if(a==='snapshot'){const sales=o.reduce((n,z)=>n+Number(z.total||0),0),ex=e.reduce((n,z)=>n+Number(z.amount||0),0),low=i.filter(z=>Number(z.qty)<=Number(z.reorder));return`${o.length} orders, ${money(sales)} sales, ${money(ex)} expenses, ${low.length} low-stock items.`}
 if(a==='low_stock'){const z=i.filter(v=>Number(v.qty)<=Number(v.reorder));return z.length?`Low stock: ${z.map(v=>`${v.name} ${v.qty} ${v.unit||''}`).join(', ')}.`:'No low-stock alerts.'}
 if(a==='list_products')return`There are ${p.length} menu items.`;
 if(a==='help')return'I can listen continuously, understand natural speech, answer business questions, add and edit records, manage stock, combos, expenses, purchases, riders and staff, take orders, checkout and print receipts.';
 if(a==='add_customer'){const z={id:Date.now(),name:x.name||'New Customer',phone:x.phone||'',address:'',points:0,visits:0};sv(K.c,[z,...c]);audit('AI_CUSTOMER_CREATE',z.name);refresh();return`Added customer ${z.name}.`}
 if(a==='add_product'){const z={id:Date.now(),name:x.name||'New Item',cat:x.category||'AI',price:Number(x.price||0),emoji:'✨',sku:`AI-${Date.now()}`,active:true,cost:0,recipe:[]};sv(K.p,[...p,z]);audit('AI_PRODUCT_CREATE',z.name);refresh();return`Added ${z.name} at ${money(z.price)}.`}
 if(a==='adjust_stock'){const z=i.find(v=>v.name.toLowerCase().includes(String(x.item||x.name||'').toLowerCase()));if(!z)return'Stock item not found.';const n=Math.max(0,Number(z.qty||0)+Number(x.quantity||0));sv(K.i,i.map(v=>v.id===z.id?{...v,qty:n}:v));audit('AI_STOCK_ADJUST',`${z.name}: ${z.qty} → ${n}`);refresh();return`${z.name} stock is now ${n} ${z.unit||''}.`}
 if(a==='create_combo'){const z={id:Date.now(),name:x.name||'AI Combo',cat:'Combos',price:Number(x.price||0),emoji:'✨',sku:`COMBO-${Date.now()}`,active:true,cost:0,recipe:[],components:[]};sv(K.p,[...p,z]);audit('AI_COMBO_CREATE',z.name);refresh();return`Created ${z.name}.`}
 if(a==='add_expense'){const z={id:Date.now(),title:x.description||x.name||'AI expense',category:x.category||'Other',amount:Number(x.amount||0),payee:'POS AI',date:new Date().toISOString().slice(0,10),method:x.method||'Cash',note:'Created by POS AI'};sv(K.e,[z,...e]);audit('AI_EXPENSE',`${z.category} ${z.amount}`);refresh();return`Recorded ${z.category} expense of ${money(z.amount)}.`}
 if(a==='add_rider'){const z={id:Date.now(),name:x.name||'New Rider',phone:x.phone||'',vehicle:'Bike',area:'',perOrder:100,perKm:25,status:'Available'};sv(K.r,[...r,z]);audit('AI_RIDER_CREATE',z.name);refresh();return`Rider ${z.name} added.`}
 if(a==='add_staff'){const z={id:Date.now(),name:x.name||'New Staff',role:x.category||'Staff',phone:x.phone||'',pin:'',salary:Number(x.amount||0),status:'Active'};sv(K.s,[...s,z]);audit('AI_STAFF_CREATE',z.name);refresh();return`Staff ${z.name} added.`}
 if(a==='create_purchase'){const z={id:Date.now(),supplierId:'',items:x.description||x.item||'',total:Number(x.amount||0),status:'Draft',invoice:`AI-${Date.now()}`};sv(K.q,[z,...q]);audit('AI_PURCHASE_CREATE',z.items);refresh();return'Purchase demand created.'}
 if(a==='delete_customer'){const z=c.find(v=>v.name.toLowerCase().includes(String(x.name||'').toLowerCase()));if(!z)return'Customer not found.';sv(K.c,c.filter(v=>v.id!==z.id));audit('AI_CUSTOMER_DELETE',z.name);refresh();return`Deleted ${z.name}.`}
 if(a==='delete_product'){const z=p.find(v=>v.name.toLowerCase().includes(String(x.name||x.item||'').toLowerCase()));if(!z)return'Product not found.';sv(K.p,p.filter(v=>v.id!==z.id));audit('AI_PRODUCT_DELETE',z.name);refresh();return`Deleted ${z.name}.`}
 if(a==='add_to_order')return addCart(x.item||x.name,x.quantity||1)?`Added ${x.quantity||1} ${x.item||x.name}.`:'Menu item not found on this POS screen.';
 if(a==='checkout'){const b=[...document.querySelectorAll('.payGrid button')].find(v=>/cash/i.test(v.innerText));if(!b||b.disabled)return'Current order is empty or not ready for payment.';b.click();audit('AI_CHECKOUT','Voice checkout');return'Order placed and sent to the kitchen.'}
 if(a==='print_receipt'){const z=o[0];if(!z)return'No sale is available to print.';await printReceipt(z);audit('AI_PRINT_RECEIPT',z.no||z.id);return`Printing receipt ${z.no||''}.`}
 return'I could not complete that action.';}

function mount(){if(document.getElementById('posAiDock'))return;const root=document.createElement('div');root.id='posAiDock';root.innerHTML=`<button id="posAiFab">✦ <span>AI</span></button><div id="posAiPanel" hidden><div class="aiHead"><div><b>POS AI Operator</b><small id="posAiStatus">GPT Realtime voice</small></div><button id="posAiClose">×</button></div><div id="posAiLog"></div><div class="aiInput"><input id="posAiInput" placeholder="Speak naturally…"><button id="posAiMic">🎙</button><button id="posAiSend">➤</button></div><div id="posAiSetup" hidden><input id="posAiKey" type="password" placeholder="OpenAI API key"><button id="posAiSave">Connect GPT Voice</button><small>Encrypted locally with Windows secure storage.</small></div></div>`;document.body.appendChild(root);const panel=root.querySelector('#posAiPanel'),log=root.querySelector('#posAiLog'),status=root.querySelector('#posAiStatus'),input=root.querySelector('#posAiInput'),setup=root.querySelector('#posAiSetup');const add=(who,m)=>{const z=document.createElement('div');z.className=`aiMsg ${who}`;z.innerHTML=`<b>${who==='user'?'You':'AI'}</b><span>${esc(m)}</span>`;log.appendChild(z);log.scrollTop=log.scrollHeight;};let pc,dc,mic;
 async function connect(){if(pc)return;status.textContent='Connecting GPT Realtime…';try{mic=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});pc=new RTCPeerConnection();mic.getTracks().forEach(t=>pc.addTrack(t,mic));const audio=document.createElement('audio');audio.autoplay=true;audio.style.display='none';document.body.appendChild(audio);pc.ontrack=e=>{audio.srcObject=e.streams[0]};dc=pc.createDataChannel('oai-events');dc.onopen=()=>{status.textContent='Listening automatically…';add('ai','Voice AI connected. I am listening.');};dc.onmessage=async ev=>{let m;try{m=JSON.parse(ev.data)}catch{return};if(m.type==='conversation.item.input_audio_transcription.completed'&&m.transcript){input.value=m.transcript;add('user',m.transcript);}if(m.type==='response.function_call_arguments.done'&&m.name==='pos_action'){let args={};try{args=JSON.parse(m.arguments||'{}')}catch{};const result=await act(args.action,args);add('ai',result);dc.send(JSON.stringify({type:'conversation.item.create',item:{type:'function_call_output',call_id:m.call_id,output:result}}));dc.send(JSON.stringify({type:'response.create'}));}};pc.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(pc.connectionState)){status.textContent='Voice disconnected. Reconnecting…';try{pc.close()}catch{}pc=null;setTimeout(connect,1200)}};const offer=await pc.createOffer();await pc.setLocalDescription(offer);const answer=await window.posDesktop.aiRealtimeConnect({sdp:offer.sdp,context:ctx()});await pc.setRemoteDescription({type:'answer',sdp:answer});status.textContent='Listening automatically…';}catch(e){status.textContent=e.message||'Voice connection failed.';add('ai',status.textContent);try{pc?.close()}catch{}pc=null;}}
 async function text(){const q=input.value.trim();if(!q)return;add('user',q);input.value='';try{const r=await window.posDesktop.aiCommand({message:q,context:ctx()});const z=await act(r.action,r.args||{});add('ai',z);if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance(z);speechSynthesis.speak(u)}}catch(e){add('ai',e.message||'AI error.')}}
 root.querySelector('#posAiFab').onclick=()=>panel.hidden=!panel.hidden;root.querySelector('#posAiClose').onclick=()=>panel.hidden=true;root.querySelector('#posAiSend').onclick=text;root.querySelector('#posAiMic').onclick=()=>connect();input.onkeydown=e=>{if(e.key==='Enter')text()};root.querySelector('#posAiSave').onclick=async()=>{const k=root.querySelector('#posAiKey').value.trim();if(!k)return;try{await window.posDesktop.setAIKey(k);setup.hidden=true;connect()}catch(e){status.textContent=e.message}};
 window.posDesktop.aiKeyStatus().then(ok=>{if(ok)connect();else{setup.hidden=false;panel.hidden=false;status.textContent='Connect GPT Voice once to enable automatic listening.'}}).catch(()=>{setup.hidden=false;panel.hidden=false});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
