const KEYS={products:'pos-products',inventory:'pos-inventory',customers:'pos-customers',suppliers:'pos-suppliers',riders:'pos-riders',staff:'pos-staff',expenses:'pos-expenses',purchases:'pos-purchases',orders:'pos-orders'};
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const id=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function say(t){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.98;u.pitch=1;speechSynthesis.speak(u)}catch{}}
function money(n){return `Rs ${Number(n||0).toLocaleString()}`}
function data(){return {products:read(KEYS.products),inventory:read(KEYS.inventory),customers:read(KEYS.customers),suppliers:read(KEYS.suppliers),riders:read(KEYS.riders),staff:read(KEYS.staff),expenses:read(KEYS.expenses),purchases:read(KEYS.purchases),orders:read(KEYS.orders)}}
function audit(action,detail){const a=read('pos-audit');a.unshift({id:id('ai'),time:new Date().toLocaleString(),user:'POS AI',action,detail});save('pos-audit',a.slice(0,1000))}
function refresh(){location.reload()}
function clickModule(name){const b=[...document.querySelectorAll('.sidebar button')].find(x=>x.innerText.toLowerCase().includes(name));if(b)b.click()}
function addToCart(name,qty){const buttons=[...document.querySelectorAll('.product')];let b=buttons.find(x=>x.innerText.toLowerCase().includes(name.toLowerCase()));if(!b){const q=name.toLowerCase();b=buttons.find(x=>x.innerText.toLowerCase().split('rs')[0].includes(q)||x.innerText.toLowerCase().includes(q.split(' ').slice(0,2).join(' ')))}if(!b)return false;for(let i=0;i<qty;i++)b.click();return true}
function printReceipt(order){const s=read('pos-settings',{}),html=`<html><head><meta charset="utf-8"><style>@page{margin:3mm;width:80mm}body{font-family:Arial;width:72mm;font-size:12px}h2{text-align:center;margin:4px 0}p{margin:3px 0}.line{display:flex;justify-content:space-between}.total{font-size:16px;font-weight:bold;border-top:1px solid #000;padding-top:5px;margin-top:6px}</style></head><body><h2>${esc(s.companyName||'MK Pizza & Ice Bar')}</h2><p style="text-align:center">${esc(s.address||'')}<br>${esc(s.phone||'')}</p><p>Order: ${esc(order.no||order.id)}<br>${new Date().toLocaleString()}<br>Payment: ${esc(order.method||'Cash')}</p>${(order.items||[]).map(x=>`<div class="line"><span>${x.qty} × ${esc(x.name)}</span><span>${money(x.qty*x.price)}</span></div>`).join('')}<div class="line total"><span>TOTAL</span><span>${money(order.total)}</span></div><p style="text-align:center;margin-top:12px">Thank you!</p></body></html>`;return window.posDesktop?.print?window.posDesktop.print({html,pageSize:'A4'}):Promise.resolve(false).then(()=>false)}
function execute(raw,ui){const t=raw.trim(),l=t.toLowerCase(),d=data();
 let m;
 if((m=l.match(/(?:add|create|new)\s+(?:customer|client)\s+(.+?)(?:\s+(?:phone|number)\s+([\d+ -]+))?$/i))){const row={id:Date.now(),name:m[1].trim(),phone:m[2]||'',address:'',points:0,visits:0};save(KEYS.customers,[...d.customers,row]);audit('AI_CUSTOMER_CREATE',row.name);return `Added customer ${row.name}.`}
 if((m=l.match(/(?:add|create|new)\s+(?:product|item)\s+(.+?)(?:\s+(?:price|at)\s+(\d+(?:\.\d+)?))?$/i))){const row={id:Date.now(),name:m[1].trim(),cat:'AI',price:Number(m[2]||0),emoji:'✨',sku:`AI-${Date.now()}`,active:true,cost:0,recipe:[]};save(KEYS.products,[...d.products,row]);audit('AI_PRODUCT_CREATE',row.name);return `Added product ${row.name} at ${money(row.price)}.`}
 if((m=l.match(/(?:adjust|change|increase|decrease|set)\s+(?:stock|inventory)\s+(?:for\s+)?(.+?)\s+(?:by|to|=)\s*(-?\d+(?:\.\d+)?)/i))){const item=d.inventory.find(x=>x.name.toLowerCase().includes(m[1].trim()));if(!item)return 'I could not find that stock item.';const v=Number(m[2]),qty=l.includes(' set ')?Math.max(0,v):Math.max(0,Number(item.qty||0)+(l.includes('decrease')||l.includes('by -')?-Math.abs(v):v));save(KEYS.inventory,d.inventory.map(x=>x.id===item.id?{...x,qty}:x));audit('AI_STOCK_ADJUST',`${item.name}: ${item.qty} → ${qty}`);return `${item.name} stock is now ${qty} ${item.unit||''}.`}
 if(/(?:make|create|add)\s+(?:a\s+)?(?:deal|combo)/i.test(l)){m=t.match(/(?:deal|combo)\s+(.+?)(?:\s+(?:for|at|price)\s+(\d+(?:\.\d+)?))?$/i);const row={id:Date.now(),name:m?.[1]||'AI Combo',cat:'Combos',price:Number(m?.[2]||0),emoji:'✨',sku:`COMBO-${Date.now()}`,active:true,cost:0,recipe:[]};save(KEYS.products,[...d.products,row]);audit('AI_COMBO_CREATE',row.name);return `Created ${row.name}. You can edit its component items in Menu & Combos.`}
 if((m=l.match(/(?:add|create|record)\s+(?:expense|cost)\s+(.+?)\s+(?:rs\.?|pkr)?\s*(\d[\d,]*(?:\.\d+)?)/i))){const cats=['Salary','Staff-Food','Rent','Utilities','Demands','Fuel','Wastage','Packaging','Maintenance','Marketing','Transport'];const cat=cats.find(x=>l.includes(x.toLowerCase()))||'Other';const row={id:Date.now(),title:m[1].trim(),category:cat,amount:Number(m[2].replaceAll(',','')),payee:'AI command',date:new Date().toISOString().slice(0,10),method:'Cash',note:'Created by POS AI'};save(KEYS.expenses,[row,...d.expenses]);audit('AI_EXPENSE',`${cat} ${row.amount}`);return `Recorded ${cat} expense of ${money(row.amount)}.`}
 if((m=l.match(/(?:add|create|new)\s+rider\s+(.+?)(?:\s+(?:phone|number)\s+([\d+ -]+))?$/i))){const row={id:Date.now(),name:m[1].trim(),phone:m[2]||'',vehicle:'Bike',area:'',perOrder:100,perKm:25,status:'Available'};save(KEYS.riders,[...d.riders,row]);audit('AI_RIDER_CREATE',row.name);return `Rider ${row.name} added.`}
 if((m=l.match(/(?:add|create|new)\s+(?:staff|employee)\s+(.+)$/i))){const row={id:Date.now(),name:m[1].trim(),role:'Staff',phone:'',pin:'',salary:0,status:'Active'};save(KEYS.staff,[...d.staff,row]);audit('AI_STAFF_CREATE',row.name);return `Staff profile ${row.name} added.`}
 if((m=l.match(/(?:add|create|new)\s+(?:purchase|demand|po)\s+(.+)$/i))){const row={id:Date.now(),supplierId:d.suppliers[0]?.id||'',items:m[1].trim(),total:0,status:'Draft',invoice:`AI-${Date.now()}`};save(KEYS.purchases,[...d.purchases,row]);audit('AI_PURCHASE_CREATE',row.items);return `Purchase demand created: ${row.items}.`}
 if((m=l.match(/(?:delete|remove)\s+(?:customer|client)\s+(.+)$/i))){const q=m[1].trim(),row=d.customers.find(x=>x.name.toLowerCase().includes(q));if(!row)return 'Customer not found.';save(KEYS.customers,d.customers.filter(x=>x.id!==row.id));audit('AI_CUSTOMER_DELETE',row.name);return `Deleted customer ${row.name}.`}
 if((m=l.match(/(?:delete|remove)\s+(?:product|item)\s+(.+)$/i))){const q=m[1].trim(),row=d.products.find(x=>x.name.toLowerCase().includes(q));if(!row)return 'Product not found.';save(KEYS.products,d.products.filter(x=>x.id!==row.id));audit('AI_PRODUCT_DELETE',row.name);return `Deleted product ${row.name}.`}
 if(/^(?:add|order|put)\s+\d+\s+/.test(l)){m=l.match(/^(?:add|order|put)\s+(\d+)\s+(.+)$/);const qty=Number(m[1]),name=m[2].replace(/\s+(?:please|to the order)$/,'').trim();if(addToCart(name,qty)){return `Added ${qty} ${name} to the current order.`}return 'I could not find that menu item on the current POS screen.'}
 if(/(?:place|submit|pay|complete)\s+(?:the\s+)?order|checkout|take payment/i.test(l)){const b=[...document.querySelectorAll('.payGrid button')].find(x=>/cash/i.test(x.innerText));if(b&&!b.disabled){b.click();return 'Order placed and sent to the kitchen.'}return 'The current order is empty or the POS is not ready for payment.'}
 if(/print\s+(?:receipt|sale)|receipt\s+(?:print|reprint)/i.test(l)){const o=d.orders[0];if(!o)return 'There is no sale to print yet.';printReceipt(o);audit('AI_PRINT_RECEIPT',o.no||o.id);return `Printing receipt ${o.no||''}.`}
 if(/(?:monitor|business|sales|revenue|performance|how are we|dashboard)/i.test(l)){const sales=d.orders.reduce((s,o)=>s+Number(o.total||0),0),low=d.inventory.filter(x=>Number(x.qty)<=Number(x.reorder)),exp=d.expenses.reduce((s,x)=>s+Number(x.amount||0),0);return `Business monitor: ${d.orders.length} orders, ${money(sales)} sales, ${money(exp)} expenses, ${low.length} low-stock items.`}
 if(/(?:what|show|tell).*(?:stock|inventory)|low stock|reorder/i.test(l)){const low=d.inventory.filter(x=>Number(x.qty)<=Number(x.reorder));return low.length?`Low stock: ${low.map(x=>`${x.name} ${x.qty} ${x.unit||''}`).join(', ')}.`:'No low-stock alerts.'}
 if(/help|what can you do/i.test(l))return 'I can add or delete products and customers, adjust stock, create combos and deals, add riders and staff, create purchases and expenses, monitor sales, take voice orders, place orders and print receipts.';
 return 'I did not understand that command. Try “add 2 Crispy Chicken Burger”, “adjust stock Cheese by -2”, “make combo Burger and Fries for 999”, or “add customer Ali phone 0300…”.';}
function mount(){if(document.getElementById('posAiDock'))return;const root=document.createElement('div');root.id='posAiDock';root.innerHTML=`<button id="posAiFab" aria-label="POS AI">✦ <span>AI</span></button><div id="posAiPanel" hidden><div class="aiHead"><div><b>POS AI Operator</b><small>Voice + business actions</small></div><button id="posAiClose">×</button></div><div id="posAiStatus">Ready. Say or type a command.</div><div class="aiQuick"><button data-c="What are sales today?">Sales</button><button data-c="What is low stock?">Stock</button><button data-c="What can you do?">Help</button></div><div id="posAiLog"></div><div class="aiInput"><input id="posAiInput" placeholder="Say: add 2 burgers…"><button id="posAiMic">🎙</button><button id="posAiSend">➤</button></div></div>`;document.body.appendChild(root);const panel=root.querySelector('#posAiPanel'),logBox=root.querySelector('#posAiLog'),input=root.querySelector('#posAiInput');const add=(who,msg)=>{const d=document.createElement('div');d.className=`aiMsg ${who}`;d.innerHTML=`<b>${who==='user'?'You':'AI'}</b><span>${esc(msg)}</span>`;logBox.appendChild(d);logBox.scrollTop=logBox.scrollHeight};const run=()=>{const q=input.value.trim();if(!q)return;add('user',q);const msg=execute(q);add('ai',msg);say(msg);input.value='';setTimeout(()=>{if(/added|created|deleted|updated|recorded|placed|printing/i.test(msg))refresh()},700)};root.querySelector('#posAiFab').onclick=()=>panel.hidden=!panel.hidden;root.querySelector('#posAiClose').onclick=()=>panel.hidden=true;root.querySelector('#posAiSend').onclick=run;input.onkeydown=e=>{if(e.key==='Enter')run()};root.querySelectorAll('.aiQuick button').forEach(b=>b.onclick=()=>{input.value=b.dataset.c;run()});const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){const r=new SR();r.lang='en-PK';r.continuous=false;r.interimResults=false;r.onstart=()=>root.querySelector('#posAiStatus').textContent='Listening…';r.onend=()=>root.querySelector('#posAiStatus').textContent='Ready. Say or type a command.';r.onerror=e=>root.querySelector('#posAiStatus').textContent=`Voice error: ${e.error}`;r.onresult=e=>{input.value=e.results[0][0].transcript;run()};root.querySelector('#posAiMic').onclick=()=>r.start()}else{root.querySelector('#posAiMic').disabled=true;root.querySelector('#posAiStatus').textContent='Voice recognition is unavailable in this Windows runtime; typing remains available.'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();