const SESSION='pos-auth-session';
const DEFAULT_USERS=[
  {name:'Admin Manager',role:'Manager',pin:'1234'},
  {name:'Cashier',role:'Cashier',pin:'1111'},
  {name:'Kitchen',role:'Kitchen',pin:'2222'}
];
const permissions={Manager:['*'],Cashier:['Point of Sale','Kitchen Display','Customers & Loyalty','Tables & Reservations'],Kitchen:['Kitchen Display']};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const read=(k,d)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):d}catch{return d}};
function users(){const staff=read('pos-staff',[]);const source=staff.filter(x=>x&&x.name&&x.pin).map(x=>({name:x.name,role:x.role||'Staff',pin:String(x.pin)}));return [...DEFAULT_USERS,...source.filter(x=>!DEFAULT_USERS.some(d=>d.name===x.name))];}
function session(){try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch{return null}}
function allowed(role,label){const p=permissions[role]||permissions.Cashier;return p.includes('*')||p.includes(label)}
function styleLogin(){const s=document.createElement('style');s.textContent=`#posAuth{position:fixed;inset:0;z-index:100000;display:grid;place-items:center;background:radial-gradient(circle at 50% 0,#28234f 0,#0a0e16 55%,#070a10 100%);font-family:Arial,sans-serif;color:#f7f9fc}#posAuth .authCard{width:min(430px,92vw);padding:34px;border:1px solid #343e50;border-radius:24px;background:linear-gradient(145deg,#151c29,#0d131d);box-shadow:0 30px 100px #0009}#posAuth .logo{width:58px;height:58px;border-radius:17px;display:grid;place-items:center;background:linear-gradient(135deg,#9b8cff,#5b4ce2);font-size:30px;font-weight:800;box-shadow:0 10px 30px #5b4ce244}#posAuth h1{margin:20px 0 5px;font-size:27px}#posAuth p{margin:0;color:#8996a9;font-size:13px;line-height:1.5}#posAuth label{display:block;margin-top:18px;color:#aeb8c7;font-size:12px;font-weight:700}#posAuth input{width:100%;height:48px;margin-top:7px;padding:0 13px;border:1px solid #303b4d;border-radius:12px;background:#090e16;color:#fff;outline:none;font-size:15px}#posAuth .pinWrap{position:relative}#posAuth .pinWrap input{padding-right:48px}#posAuth .eye{position:absolute;right:7px;bottom:7px;width:34px;height:34px;border-radius:9px;background:#182130;color:#aeb9c8}#posAuth .login{width:100%;height:48px;margin-top:22px;border:0;border-radius:12px;background:linear-gradient(135deg,#9184ff,#6355e9);color:white;font-weight:800;font-size:14px}#posAuth .hint{margin-top:14px;font-size:11px;color:#69778b;text-align:center}#posAuth .error{min-height:18px;margin-top:9px;color:#ff7f8b;font-size:12px;text-align:center}#posAuth .accounts{display:flex;gap:7px;margin-top:16px;flex-wrap:wrap}#posAuth .accounts button{flex:1;min-width:30%;height:32px;border:1px solid #2b3545;border-radius:8px;background:#141c28;color:#aeb8c7;font-size:11px}#posAuth .lock{margin-top:20px;padding-top:16px;border-top:1px solid #202a38;font-size:10px;color:#657287;text-align:center}.posPermissionDenied{opacity:.35!important;pointer-events:none!important}`;document.head.appendChild(s)}
function build(){if(location.search.includes('display=customer')||document.getElementById('posAuth'))return;styleLogin();const root=document.createElement('div');root.id='posAuth';root.innerHTML=`<div class="authCard"><div class="logo">F</div><h1>Welcome back</h1><p>Sign in to Findupto POS. Access is controlled by your staff role and local permissions.</p><label>Username / Staff Name<input id="authUser" autocomplete="username" placeholder="e.g. Admin Manager"></label><label>PIN<div class="pinWrap"><input id="authPin" type="password" inputmode="numeric" autocomplete="current-password" placeholder="Enter PIN"><button class="eye" id="authEye" type="button" aria-label="Show PIN">◉</button></div></label><div id="authError" class="error"></div><button id="authLogin" class="login">Sign in securely</button><div class="accounts"><button data-user="Admin Manager" data-pin="1234">Manager</button><button data-user="Cashier" data-pin="1111">Cashier</button><button data-user="Kitchen" data-pin="2222">Kitchen</button></div><div class="lock">Offline-first authentication · role permissions enforced locally</div></div>`;document.body.appendChild(root);const u=root.querySelector('#authUser'),p=root.querySelector('#authPin'),err=root.querySelector('#authError');root.querySelector('#authEye').onclick=()=>{const show=p.type==='password';p.type=show?'text':'password';root.querySelector('#authEye').textContent=show?'◉':'◎';root.querySelector('#authEye').setAttribute('aria-label',show?'Hide PIN':'Show PIN')};root.querySelectorAll('.accounts button').forEach(b=>b.onclick=()=>{u.value=b.dataset.user;p.value=b.dataset.pin;p.type='password'});const login=()=>{const hit=users().find(x=>x.name.toLowerCase()===u.value.trim().toLowerCase()&&String(x.pin)===p.value.trim());if(!hit){err.textContent='Invalid username or PIN.';return}localStorage.setItem(SESSION,JSON.stringify({name:hit.name,role:hit.role,at:Date.now()}));root.remove();applyPermissions(hit.role);injectUserTools(hit)};root.querySelector('#authLogin').onclick=login;p.onkeydown=e=>{if(e.key==='Enter')login()};u.onkeydown=e=>{if(e.key==='Enter')p.focus()}}
function applyPermissions(role){const apply=()=>{document.querySelectorAll('.sidebar nav button').forEach(b=>{const label=b.title||b.innerText.trim();const ok=allowed(role,label);b.classList.toggle('posPermissionDenied',!ok);b.title=ok?label:`${label} · Restricted for ${role}`;});document.body.dataset.posRole=role};apply();new MutationObserver(apply).observe(document.body,{subtree:true,childList:true})}
function injectUserTools(s){const run=()=>{const bottom=document.querySelector('.sideBottom');if(!bottom||document.getElementById('posLogout'))return;const b=document.createElement('button');b.id='posLogout';b.textContent=`Sign out · ${s.name}`;b.style='width:100%;margin-top:7px;height:32px;border:1px solid #293447;border-radius:8px;background:#141b26;color:#aeb8c7;font-size:10px;cursor:pointer';b.onclick=()=>{localStorage.removeItem(SESSION);location.reload()};bottom.appendChild(b)};setTimeout(run,50);new MutationObserver(run).observe(document.body,{subtree:true,childList:true})}
function maskPins(){document.querySelectorAll('table').forEach(t=>{const heads=[...t.querySelectorAll('th')];const pin=heads.findIndex(h=>/\bpin\b/i.test(h.textContent));if(pin<0)return;t.querySelectorAll('tbody tr').forEach(r=>{const c=r.children[pin];if(c)c.textContent='••••';});});document.querySelectorAll('label').forEach(l=>{if(!/pin/i.test(l.firstChild?.textContent||l.textContent))return;const input=l.querySelector('input');if(!input||l.dataset.pinSecured)return;l.dataset.pinSecured='1';input.type='password';const b=document.createElement('button');b.type='button';b.textContent='◉';b.style='margin-left:6px;height:28px;border:1px solid #293447;border-radius:6px;background:#151d29;color:#aeb8c7;cursor:pointer';b.onclick=()=>{input.type=input.type==='password'?'text':'password'};l.appendChild(b)})}
function enforce(){const s=session();if(!s){build();return}applyPermissions(s.role);injectUserTools(s);maskPins();const o=new MutationObserver(maskPins);o.observe(document.body,{subtree:true,childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enforce);else enforce();